language: node_js
node_js:
  - "7"
  - "10"
  - "11"
  - "12"
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
